Can we use Bayesian statistics to estimate when Mambo Number 5 appeared based on the names of the women that appear in the song?

## Bayesian inference

We can answer the above question using the Bayes Formula: 

$$
\Pr(Y_R|N) = \frac{\Pr(N|Y_R) \Pr(Y_R)}{\Pr(N)},
	$$
where the posterior distribution $\Pr(Y_R|N)$ describes the probability of the release year ($Y_R$) _given_ the nine names $N = {Angela, Pamela, Sandra, Rita, Monica, Erica, Tina, Mary, Jessica}$ that appear in _Mambo No. 5_. On the right-hand side, the likelihood function $\Pr(N|Y_R)$ describes the probability of observing the names conditioned on $Y_R$. Finally, $\Pr(Y_R)$ is our prior probability distribution, and $\Pr(N)$ is the marginal distribution.

We can use the frequency of baby names for each year to calculate these probabilities. However, it is important to note that while _Mambo No. 5_ was released in 1999, it would be wrong to assume that we only need to look at popular baby names in 1999. Lou Bega wasn’t meeting newborn infants but was most likely referring to 20–35-year-old women—so we should be **looking at the popularity of names between 1960 and 1980**. Let us describe the age of the women as $\alpha$, such that we can back-calculate the birth year ($Y_R - \alpha_i$). For example, if we assume that the release year is 1980 and the women are 20 years old, we would be looking at the popularity of girls’ names in 1960.

For simplicity, I will assume that all women are of the same age ranging from 20 to 35 years old. Therefore, the probability of a name given the release and the specific age:

$$
\Pr(N = N_i|\alpha =\alpha_j, Y_R) = \Pr(N_i, Y_R - a_j).
$$
For all the names:
$$
\Pr(N |\alpha =\alpha_j, Y_R) = \prod_{i=1}^9\Pr(N_i, Y_R - a_j).
$$
Assuming a uniform probability distribution for the ages, we are saying that there is an equal probability that a woman is 20 or 30:

$$
Pr(a = a_j) = \frac{1}{35 - 20} = \frac{1}{16}.
$$
And we can marginalize over the ages using the law of total probability:

$$
\Pr(N|Y_R) =\frac{1}{16} \sum_{a_j = a_{min}}^{a_{max}}\prod_{i=1}^9\Pr(N_i, Y_R - a_j),
$$
and our posterior distribution is then: 
$$\Pr(Y_R|N) \propto \frac{1}{16} \Pr(Y) \sum_{a_j = a_{min}}^{a_{max}}\prod_{i=1}^9\Pr(N_i, Y_R - a_j), $$
where we assume that the prior $\Pr(Y)$ is a uniform distribution ranging from 1980 to 2005. 
